name: Scheduled Scan

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas gspread google-auth google-auth-oauthlib google-auth-httplib2

      - name: Run main market scanner
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          python crypto_scanner.py

      - name: Run on-chain data fetcher
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          python .github/scripts/fetch_onchain.py

      - name: Run dev activity fetcher
        run: |
          python .github/scripts/fetch_dev_activity.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scan_data
          path: |
            scan_output.csv
            onchain_output.csv
            dev_output.csv

      - name: Upload to Google Sheets
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python .github/scripts/upload_to_sheets.py
